project:
  type: website

website:
  title: "Pinn (Aiqi) Xu Projects"
  #title-separator: " | "
  description: "A collection of projects by Pinn (Aiqi) Xu, showcasing work in data science, machine learning, and software development."
  favicon: src/img/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: projects/index.qmd
      - text: About
        href: about/index.qmd
  sidebar:
    style: 'docked'
    background: light
    # search: true
    contents: auto

format:
  html:
    # self-contained: false
    theme:
      - minty
    syntax-highlighting: pygments
    css: styles/styles.css
    toc: true
    code-tools: true
      # toggle: true
      # source: true
      # caption: "hi"
    code-fold: true
    # code-summary: "Show the code"
    include-after-body: fix-code-fold.html

editor: visual

