project:
  type: website

website:
  title: "Pinn (Aiqi) Xu"
  #title-separator: " | "
  description: "A collection of projects by Pinn (Aiqi) Xu, showcasing work in data science, machine learning, and software development."
  favicon: src/img/favicon/spark.ico

  back-to-top-navigation: true
  page-footer: 
    left: "© Copyright 2026, Pinn (Aiqi) Xu. All rights reserved." 
  
  repo-url: https://github.com/Pinn32/dv-projects
  repo-actions: [source, issue]
  repo-link-target: _blank

  #############################################################################
  navbar:
    tools: 

    ###### Language Switch / Translation ######
      - icon: translate
        menu: 
          - text: English
            href: "#"
            # id: switch-en # 没有 id 属性
            # href: "#"
            # class: lang-switch
          - text: 中文
            href: "#"
            # id: switch-zh # 没有 id 属性
            # href: "#"
            # class: lang-switch


      - icon: github
        href: https://github.com/Pinn32/dv-projects
        # menu:
        #   - text: Source Code
        #     href: https://github.com/Pinn32/dv-projects
        #   - text: Report a Bug
        #     href: https://github.com/Pinn32/dv-projects/issues
      - icon: linkedin
        href: https://www.linkedin.com/in/aiqi-xu-71943b378/

      # - icon: https://cdn.brandfetch.io/idriarYq6Q/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1686028240869
      #   href: https://twitter.com/<insert_twitter_id_here>

    left:
      # - href: index.qmd
      #   text: Home
      - text: Projects
        href: en/projects/index.qmd
      - text: Tutorials
        href: en/tutorials/index.qmd
      - text: Hobbies
        href: en/hobbies/index.qmd
      # - text: About
      #   href: about/index.qmd
    
    # right: 
    #   - text: EN
    #     href: index.qmd
    #   - text: 中文
    #     href: index.zh.qmd


  #############################################################################
  sidebar:
    - id: en-sidebar
      logo: false
      style: 'docked'
      collapse-level: 1
      contents:
        - section: "Projects"
          href: en/projects/index.qmd
          contents:
            - text: "Evolution of Online AI Discourse"
              href: en/projects/ai-discourse/index.qmd
            - text: "Twitter Sentiment Analysis of Catalan Referendum"
              href: en/projects/catalan-referendum/index.qmd
            - text: "Global Visa Cost Analysis"
              href: en/projects/global-visa-cost/index.qmd
            - text: "Student Social Media Usage & Addiction"
              href: en/projects/student-media-usage/index.qmd
            - text: "Most Streamed Songs on Spotify"
              href: en/projects/most-streamed-songs/index.qmd
        - section: "Tutorials"
          href: en/tutorials/index.qmd
          contents:
            - text: "Data Processing"
              href: en/tutorials/data-processing/index.qmd
            - text: "Amounts and Distribution"
              href: en/tutorials/amounts-and-distribution/index.qmd
            - text: "Multivariate Plots"
              href: en/tutorials/multivariate-plots/index.qmd
            - text: "Sankey & Network Diagrams"
              href: en/tutorials/sankey-and-network/index.qmd
            - text: "R Tips"
              href: en/tutorials/r-tips/index.qmd
        - text: "About"
          href: en/about/index.qmd
    - id: zh-sidebar
      logo: false
      style: 'docked'
      collapse-level: 1
      contents:
        - section: "项目"
          href: zh/projects/index.qmd
          contents:
            - text: "网络AI话语的演变"
              href: zh/projects/ai-discourse/index.qmd
            - text: "Twitter 加泰罗尼亚公投情感分析"
              href: zh/projects/catalan-referendum/index.qmd
            - text: "全球签证费用分析与交互式可视化"
              href: zh/projects/global-visa-cost/index.qmd
            - text: "学生社交媒体使用与幸福感分析"
              href: zh/projects/student-media-usage/index.qmd
            - text: "Spotify 最高播放量歌曲: 音乐特征与受众趋势分析"
              href: zh/projects/most-streamed-songs/index.qmd
        - section: "教程"
          href: zh/tutorials/index.qmd
          contents:
            - text: "数据清理"
              href: zh/tutorials/data-processing/index.qmd
            - text: "数量与分布可视化"
              href: zh/tutorials/amounts-and-distribution/index.qmd
            - text: "多变量图表"
              href: zh/tutorials/multivariate-plots/index.qmd
            - text: "桑基图与网络图"
              href: zh/tutorials/sankey-and-network/index.qmd
            - text: "R语言技巧"
              href: zh/tutorials/r-tips/index.qmd
        - text: "关于"
          href: zh/about/index.qmd


###############################################################################
format:
  html:
    # self-contained: false
    smooth-scroll: true
    theme: minty
    from: markdown+mark
    syntax-highlighting: pygments
    css:
      - ./src/styles/styles.css
      - ./src/styles/portfolio.css
      - ./src/styles/projects.css
    
    ###### JS Scripts ######
    include-after-body:
      - ./src/scripts/fix-code-fold.html
      - ./src/scripts/lang-switch.html
      - ./src/scripts/fix-sidebar-toggle.html
      - ./src/scripts/fix-navbar-active.html
    
    toc: true
    code-tools: true
      # toggle: true
      # source: true
      # caption: "hi"
    code-fold: true
    # code-summary: "Show the code"


##############################################################################

# lang: en
brand: _brand.yml
editor: source
filters: 
  - src/filters/reading-stats.lua  # for reading time

